# Generated by Django 5.0.4 on 2024-04-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data_lancamento', models.CharField(max_length=9)),
                ('preco', models.CharField(max_length=11)),
            ],
        ),
    ]
